on: [push]

jobs:
  PSScriptAnalyzer_job:
    runs-on: ubuntu-latest
    name: PSScriptAnalyzer
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: PSScriptAnalyzer
      uses: mkletz/SecOps-PowerShell-PSScriptAnalyzer@v1
      with:
        path: 'src'